name = "vtm-sheet"
compatibility_date = "2024-01-01"
pages_build_output_dir = "MS"

[[d1_databases]]
binding       = "vtm_database"
database_name = "vampire"
database_id   = "dc3019ae-ccf2-478e-85e6-bf9cd03ea05b"

[[kv_namespaces]]
binding = "VTM_SESSIONS"
id      = "a6a869468d534927bb1a56bfd4828c6c"
